============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/webmaster/PyProjects/pytest-practice/tests
plugins: anyio-3.7.1, asyncio-0.21.1
asyncio: mode=strict
collected 2 items

test_code.py .F                                                          [100%]

=================================== FAILURES ===================================
__________________________ test_user_name_validation ___________________________

    def test_user_name_validation():
        with pytest.raises(ValueError) as e:
           # sample_code.user_name_validation(None)
>          1/0
E          ZeroDivisionError: division by zero

test_code.py:20: ZeroDivisionError
=========================== short test summary info ============================
FAILED test_code.py::test_user_name_validation - ZeroDivisionError: division ...
========================= 1 failed, 1 passed in 0.06s ==========================
